spring:
  application:
    name: tgbotforbooking
  datasource:
    hikari:
      minimum-idle: 2
      maximum-pool-size: 4
  jpa:
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    show-sql: true
  liquibase:
    enabled: true
    drop-first: false
    change-log: 'classpath:db/changelog/db.changelog-master.xml'
    default-schema: public
    contexts: update
bot:
  name: tgbotforbooking
panel:
  user-name: '${WP_USERNAME}'
  pass: '${WP_PASS}'
schedule:
  start-day: '${SCHEDULE_START_DAY:14:30}'
  end-day: '${SCHEDULE_START_DAY:19:30}'
  slot-duration: '${SLOT_DURATION:PT30M}'
logging:
  level:
    org:
      springframework:
        jdbc:
          datasource:
            DataSourceUtils: INFO
      hibernate:
        engine:
          jdbc:
            env:
              internal:
                JdbcEnvironmentInitiator: INFO
        type:
          descriptor:
            sql:
              BasicBinder: INFO
        SQL: INFO
    com:
      zaxxer:
        hikari:
          HikariDataSource: INFO
server:
  port: 8888
  ssl:
    enabled: true
    key-store-type: PKCS12
    key-store: 'classpath:keystore.p12'
    key-alias: tgbotforbooking
    key-store-password: '${KS_PASS}'
google:
  calendar:
    user-id: '${GOOGLE_USER_ID}'
    credentials-file-path: credentials.json
    tokens-path: tokens