spring:
  application:
    name: tgbotforbooking
  datasource:
    url: '${DATABASE_URL}'
    username: '${DATABASE_USERNAME}'
    password: '${DATABASE_PASSWORD}'
    driver-class-name: org.postgresql.Driver
    hikari:
      minimum-idle: 2
      maximum-pool-size: 4
  jpa:
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    show-sql: true
  data:
    redis:
      host: redis
      port: 6379
  liquibase:
    enabled: true
    drop-first: false
    change-log: 'classpath:db/changelog/db.changelog-master.xml'
    default-schema: public
    contexts: update
bot:
  name: tgbotforbooking
  token: '${BOT_TOKEN}'
logging:
  level:
    org:
      springframework:
        jdbc:
          datasource:
            DataSourceUtils: INFO
      hibernate:
        engine:
          jdbc:
            env:
              internal:
                JdbcEnvironmentInitiator: INFO
        type:
          descriptor:
            sql:
              BasicBinder: INFO
        SQL: INFO
    com:
      zaxxer:
        hikari:
          HikariDataSource: INFO
google:
  calendar:
    user_id: '${GOOGLE_USER_ID}'
    credentials_file_path: credentials.json
    tokens_path: tokens
